[project]
name = "hotel-booking-management-system-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.4.3",
    "psycopg2>=2.9.10",
]
